### PR TITLE
post acceptance modifications

### PR DESCRIPTION
**Pull request by mr-c**
To-do:
- [ ] expand the 2nd paragraph of the abstract to enhance understandability to non-insiders.
- [ ] explain the need for a new standard
- [ ] provide a timeline beyond the second draft.

### CODE REVIEW

**Comment by mr-c** [comment]
Updated abstract is due June 5th, 2015.

It still needs to render to a single page; we can explore formatting changes to squeeze a few more sentences in, if needed.

**Comment by mr-c** [comment]
Announcement is at https://groups.google.com/d/msg/common-workflow-language/8Z_OXknRpUY/55looxSJoy0J

Re: #3 we can mention the interoperability testing going on at the codefest

**Comment by mr-c** [comment]
- [ ] add 'wfdesc are not runnable' w/ citation; hat tip to @ntijanic

**Comment by mr-c** [comment]
@ntijanic can you expand on what you meant by 'not runnable'?

**Comment by ghost** [comment]
I can try :)

wfdesc does not describe any execution semantics. It only describes an abstract workflow - a DAG of components, each with own input and output ports. CWL keeps the abstract description of wfdesc, but expands it with additional properties and specification on how to execute each component and the workflow itself.

Does that make sense?

**Comment by mr-c** [comment]
Yep! That was my guess but I wanted to make sure

**Pull request closed without merging**
